# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  

- script: echo Hello, world!
    npm install
    npm run build
  displayName: 'npm install and build'
 
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk-awsp'
    testType: 'app'
    targetFile: 'https://github.com/slatersnyk/juice-shop/blob/master/Dockerfile'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'juice-shop'
    organization: '3bcce633-7bcc-46fc-88de-b50db8eeeb16'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
